#! /bin/bash

feh --bg-fill ~/wallpapers/mountains.jpg &

#while true; do
#	feh --randomize --bg-fill ~/wallpapers/*
#	sleep 300
#done &

slstatus &

picom --corner-radius 14 --round-borders 14 &

exec dwm

