#!/bin/bash

#dmenu_path | dmenu "$@" | ${SHELL:-"/bin/sh"} 

PROGRAM=$(dmenu_path | dmenu "$@")

if [[ $PROGRAM == "ranger" || $PROGRAM == "htop" ]] # change this so it works for more terminal apps (use an array)
then
	st -e $PROGRAM
else
	$PROGRAM | ${SHELL:-"/bin/sh"}
fi	
